name: idp

services:
  vllm-vl:
    environment:
      TRANSFORMERS_CACHE: /models/vl/hf-cache
      HF_HOME: /models/vl/hf-cache
    volumes:
      - ${IDP_MODELS_ROOT:-../../transfer/models}/vl_hf_cache:/models/vl/hf-cache:rw

  vllm-llm:
    environment:
      TRANSFORMERS_CACHE: /models/llm/hf-cache
      HF_HOME: /models/llm/hf-cache
    volumes:
      - ${IDP_MODELS_ROOT:-../../transfer/models}/llm_hf_cache:/models/llm/hf-cache:rw

networks:
  idp_internal:
    internal: true
